#!/bin/bash
# this script is just for eddy_cuda

list=$1
N=`wc ${1} | awk '{print $1}'`

currentdir=/lustre/atlas/proj-shared/med104/data/NKI/eddy_nki
#nki=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/NKI/data

git=/lustre/atlas/proj-shared/med104/data/NKI/embarc/
CMD_batch=$git/job/cmd1.batch.trac1.${list}
rm -rf $CMD_batch

#######################################################################################################
cat<<EOC >$CMD_batch
#!/bin/bash
#PBS -A med104
#PBS -N eddy
#PBS -m abe
#PNS -M jiook.cha@nyspi.columbia.edu
#PBS -j oe
#PBS -l walltime=2:00:00,nodes=$N
#PBS -l gres=atlas1%atlas2

OMP_NUM_THREADS=16
echo start............................................

EOC

#######################################################################################################
i=1
for s in `cat \$git/\$list`

do

  CMD=$git/job/eddy.olcf.${s}
  rm -rf $CMD

  LOG=$git/job/log.eddy.olcf.${s}
  rm -rf $LOG

  subject=`echo $s | cut -d "_" -f1`
  sess=`echo $s | cut -d "_" -f2`

  SUBJECT=${subject}_${sess}
#echo ${SUBJECT}

cat<<EOC >$CMD
#!/bin/bash

cd $currentdir/$s
#1.
echo converting && time mrconvert *dwi.nii.gz -force mr_dwi.mif -fslgrad *dwi.bvec *dwi.bval \
            -datatype float32 -stride 0,0,0,1

# 2. denoising (time:1m)
echo denoiseing && time dwidenoise mr_dwi.mif -force mr_dwi_denoised.mif

# 3. eddy (time:60m)
echo eddy && time dwipreproc mr_dwi_denoised_gibbs_crop.mif mr_dwi_denoised_gibbs_crop_preproc.mif \
            -pe_dir AP \
            -rpe_none \
            -eddy_options " --niter=8 --fwhm=10,8,4,2,0,0,0,0 --repol --mporder=6 \
              --slspec=../my_slspec.txt --s2v_niter=10 --s2v_lambda=1 \
              --s2v_interp=trilinear -v " \
            -nocleanup -force -debug

if [ -e mr_dwi_denoised_gibbs_crop_preproc.mif ];then echo eddy is complete
else echo is NOT complete
fi
EOC
chmod +x $CMD

echo "aprun -n 1 -N 1 -d 16 $CMD > $LOG 2>&1 &">>$CMD_batch

echo "sleep 0.2">>$CMD_batch
i=$(($i+1))
echo $i
#echo "execute $CMD_sub"

done

echo "wait" >> $CMD_batch
### batch submission

echo $CMD_batch
chmod +x $CMD_batch
echo qsub $CMD_batch
